import "./globals.css";
import { Cartprovider } from '../../components/context/Cartcontext'
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Cartprovider>
        {children}
        </Cartprovider>
      </body>
    </html>
  );
}
